import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/react-app/">react-app Home</Link>
            </li>
            <li>
              <Link href="/react-app/users">react-app - Users</Link>
            </li>
            <li>
              <Link href="/next-app/">next-app - Home</Link>
            </li>
            <li>
              <Link href="/next-app/users">next-app - Users</Link>
            </li>
          </ul>
        </nav>
        <h1>This is next app</h1>
        {children}
      </body>
    </html>
  )
}
